DROP database IF EXISTS `jpa_JBD`;

CREATE database IF NOT EXISTS `jpa_JBD`;
use `jpa_JBD`;

CREATE TABLE `STUDENT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FNAME` varchar(45) DEFAULT NULL,
  `LNAME` varchar(45) DEFAULT NULL,
  `CONTACT_NO` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


INSERT INTO `STUDENT` (`ID`,`FNAME`,`LNAME`,`CONTACT_NO`) VALUES (1,'Roland','Minova','+1-408-575-1317');
INSERT INTO `STUDENT` (`ID`,`FNAME`,`LNAME`,`CONTACT_NO`) VALUES (2,'Arnold','Minova','+1-408-128-1317');